# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('is_loged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('redact_date', models.DateTimeField(verbose_name='last modified date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('post', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
