# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.2 on 2016-11-01 18:03
=======
# Generated by Django 1.10.2 on 2016-10-26 16:40
>>>>>>> 4e6d4b6b6ba00630ed7df82a6b542a3c9de17484
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
                ('picture', models.ImageField(blank=True, default='avatars/no_image.png', height_field=50, null=True, upload_to='avatars/', width_field=50)),
                ('is_loged', models.BooleanField(default=False)),
=======
                ('userName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('regDate', models.DateTimeField(verbose_name='registration date')),
                ('picture', models.ImageField(height_field=50, upload_to='avatars', width_field=50)),
>>>>>>> 4e6d4b6b6ba00630ed7df82a6b542a3c9de17484
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('redact_date', models.DateTimeField(verbose_name='last modified date')),
                ('picture', models.FileField(upload_to='static')),
=======
                ('text', models.CharField(max_length=500)),
                ('pubDate', models.DateTimeField(verbose_name='publication date')),
                ('redactDate', models.DateTimeField(verbose_name='last modified date')),
                ('picture', models.ImageField(height_field=100, upload_to='postImage', width_field=100)),
>>>>>>> 4e6d4b6b6ba00630ed7df82a6b542a3c9de17484
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
<<<<<<< HEAD
                ('post', models.ManyToManyField(to='blog.Post')),
=======
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
>>>>>>> 4e6d4b6b6ba00630ed7df82a6b542a3c9de17484
            ],
        ),
    ]
