# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='regDate',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pubDate',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='redactDate',
            new_name='redact_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
