# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161101_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, default='static/no_image.png', height_field=50, null=True, upload_to='static', width_field=50),
        ),
    ]
