# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161027_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='avatars', width_field=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
