# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161028_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, default='avatars/None/no-img.jpg', height_field=50, null=True, upload_to='avatars', width_field=50),
        ),
    ]
