# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161101_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='picture',
            new_name='image',
        ),
    ]
